# /etc/updateip/
Log:
  Level: info
  Path: /tmp/updateip.log

Provider:
  Cloudflare:
    APIKey: ""
    APIEmail: ""
    Hostname: ""

Readonly: false
Ifaces:
  External: true
  Local: false

  Regex:
    Name: "en0"
    Addr: "192.168.*"
    AutoRegister: True # will register all Interfaces that were found

output: bash