# /etc/updateip/
Readonly: true
Log:
  Level: info
  Path: /tmp/updateip.log

Provider:
  Cloudflare:
    APIKey: ""
    APIEmail: ""
    Hostname: ""

Ifaces:
  Regex:
    Name: "en0"
    Addr: "192.168.*"
    AutoRegister: True # will register all Interfaces that were found

output: bash