name: Go

on:  
  push:
    tags:
      - '*'


# workflow tasks
jobs:
  build:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
         go-version: '1.18.1' # The Go version to download (if necessary) and use.

      - name: Install dependencies
        run: |
          go version
          go mod download

      - name: Build
        run: |
          go build -buildmode exe -o build/updateip-linux-x86_64 ./main.go

          export GOARCH=arm
          export GOARM=7
          go build -buildmode exe -o build/updateip-linux-armv7l ./main.go

          export GOARCH=arm64
          go build -buildmode exe -o build/updateip-linux-aarch64 ./main.go

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: latest
          files: |
            build/updateip-linux-x86_64
            build/updateip-linux-armv7l
            build/updateip-linux-aarch64
