name: Go

on:  
  push:
    tags:
      - '*'


# workflow tasks
jobs:
  build:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
         go-version: '1.18.1' # The Go version to download (if necessary) and use.

      - name: Install dependencies
        run: |
          go version
          go mod download

      - name: Build arm
        run: |
          export GOARCH=arm
          export GOARM=7
          go build -buildmode exe -o build/updateip-linux-arm32 ./main.go

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: dist/updateip*
